#!/usr/bin/env python3

"""
code  .git/hooks/pre-commit

---

python3 ./scripts/precommit.py

git add ./gen/__init__.py
git add ./README.md

"""


import re
import subprocess
from pathlib import Path


root = Path(__file__).resolve().parent.parent

INIT_FILE = root / "gen/__init__.py"


def should_bump_version():
    """Check if git changes include root README.md, ./gen, or ./scripts folders."""
    try:
        result = subprocess.run(
            ["git", "diff", "--cached", "--name-only"],
            cwd=root,
            capture_output=True,
            text=True,
            check=True
        )
        changed_files = result.stdout.strip().split("\n")
        
        for file in changed_files:
            if not file:
                continue
            # Check if it's the root README.md
            if file == "README.md":
                return True
            # Check if it's in ./gen or ./scripts
            if file.startswith("gen/") or file.startswith("scripts/"):
                return True
        
        return False
    except subprocess.CalledProcessError:
        return False


def main():
    if not should_bump_version():
        print("No relevant changes detected. Skipping version bump.")
        return

    if not INIT_FILE.exists():
        raise SystemExit("__init__ file not found")

    text = INIT_FILE.read_text()

    m = re.search(r"\d+\.\d+\.\d+", text)
    if not m:
        print(text)
        print(m)
        raise SystemExit("Version not found")

    # Update like abacus
    major, minor, patch = map(int, m.group(0).split("."))

    patch += 1
    if patch >= 100:
        patch = 0
        minor += 1

    if minor >= 100:
        minor = 0
        major += 1

    new_version = f"{major}.{minor}.{patch}"

    new_text = f"""
__VERSION__ = "{new_version}"

# note this is auto generated by pre commit hook.
"""

    INIT_FILE.write_text(new_text)

    # f = open(root / "README.md", 'a')
    # f.write(f"<br><input type='hidden' value='{new_version}' />")
    # f.close()

    print("Version bump:", new_version)


if __name__ == "__main__":
    main()