#!/usr/bin/env python3

"""
code  .git/hooks/pre-commit

---

python3 ./scripts/precommit.py

git add ./resume/gen/__init__.py
git add ./README.md

"""


from pathlib import Path

root = Path(__file__).resolve().parent.parent

INIT_FILE = root / "resume/gen/__init__.py"


def should_bump_version():
    """Check if git changes include root README.md, ./gen, or ./scripts folders."""
    try:
        import subprocess

        result = subprocess.run(
            ["git", "diff", "--cached", "--name-only"],
            cwd=root,
            capture_output=True,
            text=True,
            check=True
        )
        changed_files = result.stdout.strip().split("\n")
        
        for file in changed_files:
            if not file:
                continue
            # Check if it's the root README.md
            if file == "README.md":
                return True
            # Check if it's in ./gen or ./scripts
            if file.startswith("gen/") or file.startswith("scripts/"):
                return True
        
        return False
    except subprocess.CalledProcessError:
        return False


def main():
    if not should_bump_version():
        print("No relevant changes detected. Skipping version bump.")
        return

    if not INIT_FILE.exists():
        raise SystemExit("__init__ file not found")

    from datetime import datetime
    now = datetime.now()
    new_version = now.strftime("%Y%m.%d.%H%M")

    new_text = f"""
__VERSION__ = "{new_version}"

# note this is auto generated by pre commit hook.
"""

    INIT_FILE.write_text(new_text)

    # f = open(root / "README.md", 'a')
    # f.write(f"<br><input type='hidden' value='{new_version}' />")
    # f.close()

    print("Version bump:", new_version)


if __name__ == "__main__":
    main()